update packer.yml

diff --git a/.github/workflows/packer.yml b/.github/workflows/packer.yml
--- a/.github/workflows/packer.yml
+++ b/.github/workflows/packer.yml
@@ -22,10 +22,14 @@ jobs:
     
       - name: "Run Packer fmt"
         run: |
-            if packer fmt --check packer/.; then
+            if ! packer fmt --check packer/.; then
             echo "Packer fmt found formatting issues. Please run 'packer fmt' locally and commit the changes."
             exit 1
             fi
     
       - name: "Run Packer validate"
-        run: "packer validate packer/."
+        run: |
+          if ! packer validate packer/.; then
+          echo "Packer validation failed. Please fix the issues and try again."
+          exit 1
+          fi
